sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
- bundle -v
- rm Gemfile.lock || true
- gem update --system
- gem update bundler
- gem --version
- bundle -v
script:
- bundle exec rake $CHECK
matrix:
- rvm: 2.4.2
  bundler_args: --without system_tests development release
  env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes 

deploy:
  provider: puppetforge
  user: CERNOps
  password:
    secure: SDBqin7XVo1T71UQ3hI4N19e177kkdpwwttFHY8ypw2VqqoJsr0H6awaB00ZU9WH/54grKDaaDbigRpd2uvWVwt91ru9jUp6Cdp5dCkes99Zl5bo5BhzDMtNZlDf4qSt7ZU/s02a5c1JxNGlVYgDWuVA5kl9soNBZ34/KB7ZrIM=
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
